version: '3.7'

services:

  localstack:
    container_name: localstack_container_consuming_sqs_messages
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1
    volumes:
      - "./scripts:/etc/localstack/init/ready.d"